lang = {
    DEFAULT: (key) => `${key} has not been translated for en-US yet.`,
    DEFAULT_LANGUAGE: 'Default Language',
    // PREFIX COMMAND
    PREFIX_REMINDER: (prefix = `@${this.client.user.tag}`) => `Current prefix${Array.isArray(prefix) ?
        `es on this server are: ${prefix.map(pre => `\`${pre}\``).join(', ')}` :
        ` in this server is set to: \`${prefix}\``
    }`,
    PREFIX_SET: (prefix) => `Префикс был сменён на \`${prefix}\``,
    CURRENT_PREFIX: (cprefix) => `Текущий префикс: \`${cprefix}\``,
    PREFIX_DESCRIPTION: 'Меняет серверный префикс/показывает текущий префикс',
    PREFIX_LENGTH: '**Вы не можете выставить префикс длинее 10 символов!**',
    // SHIT
    COOLDOWN_TITLE: 'Cooldown',
    COOLDOWN: (remaining) => `Вы должны подождать еще ${remaining} секунд${remaining === 1 ? '' : 'у'}.`,
    COMMAND_DISABLED_SERVER: 'Эта команда была выключена на этом сервере.',
    COMMAND_DISABLED_GLOBAL: 'Эта команда временно недоступна.',
    MISSING_BOTPERMS: (missing) => `У меня нет прав на выполнение этой команды, недостает: **${missing}**.`,
    NSFW: 'Эту команду можно использовать только в NSFW каналах!',
    NO_PERMISSIONS: 'У Вас нет прав на использование этой команды',
    MISSING_REQUIRED_SETTINGS: (settings) => `This server is missing the **${settings.join(', ')}** server setting${settings.length !== 1 ? 's' : ''} and thus this command cannot complete.`,
    RUNIN: (types) => `Эта команда доступна только в \`${types}\` каналах!`,
    RUNIN_NONE: (name) => `Команда \`${name}\` не настроена на выполнение в каких либо каналах.`,
    // EVAL
    EVAL_DESCRIPTION: 'Выполняет заданный код',
    EVAL_ERROR: (time, output, type) => `**Error**:${output}\n**Type**:${type}\n${time}`,
    EVAL_OUTPUT: (time, output, type) => `**Output**:${output}\n**Type**:${type}\n${time}`,
    EVAL_SENDFILE: (time, type) => `Output was too long... sent the result as a file.\n**Type**:${type}\n${time}`,
    EVAL_CONSOLE: (time, type) => `Output was too long... sent the result to console.\n**Type**:${type}\n${time}`,
    // PING
    PING: '**Pong!**\nRoundtrip took: \`Calculating...\`.\nHeartbeat: \`Calculating...\`.\nDatabase: \`Calculating...\`.\nREST: \`Calculating...\`.',
    PONG: (diff, ping, db, rest) => `**Pong!**\nRoundtrip took: \`${diff}ms\`.\nHeartbeat: \`${ping}ms\`.\nDatabase: \`${db}ms\`.\nREST: \`${rest}\`.`,
    PING_DESCRIPTION: 'Pong!',
    // INVITE
    INVITE_DESCRIPTION: 'Пригласить Bass на Ваш сервер!',
    BASS_INVITE: 'Пригласить Bass на Ваш сервер!',
    // INFO
    INFO_DESCRIPTION: 'Информация про Bass',
    // HELP
    HELP_DESCRIPTION: 'Это сообщение',
    HELP_NO_EXTENDED: 'No extended help available.',
    HELP_USAGE: (usage) => `Использование :: ${usage}`,
    HELP_EXTENDED: 'Extended Help ::',
    HELP_BOT_OWNER_ONLY: `Владелец бота`,
    HELP_MANAGE_GUILD: `Управление сервером`,
    HELP_SERVER_OWNER: `Владелец сервреа`,
    HELP_SYNTAX: (prefix) => `${prefix}команда - Описание *(Требуемые права)*\nЧто-бы получить информацию о команде, используйте ${prefix}команда и я покажу правильное использоваие\nНапример: ${prefix}volume`,
    //HELP_SYNTAX: (prefix) => `${prefix}command - Description *(Required permissions)*\nTo get informations about command usage do ${prefix}help (commandname)\nUsing command that requires args, without giving them will also give command usage info`,
    HELP_COMMANDS_STRING: `Команды`,
    HELP_COMMAND_NOT_FOUND: (command) => `Команда \`${command}\` не найдена.`,
    HELP_TITLE: 'Помощь по Bass',
    HELP_LINKS: 'Ссылки',
    HELP_SUPPORT_SERVER: 'Сервер поддержки',
    HELP_INVITE: 'Пригласить',
    HELP_VOTE: 'Проголосовать',
    // STATS
    STATS_DESCRIPTION: 'Показать статистику о Bass',
    CLUSTER: 'Кластер',
    ERROR: 'Ошибка',
    SHARDS: 'Шард',
    SERVERS: 'Сервера',
    USERS: 'Пользователи',
    CONNECTIONS: 'Соединения',
    PLAYERS: 'Плееры',
    TOTAL: 'Всего',
    CLUSTERS: 'Кластеры',
    //EVENTS_RECIEVED: 'Events recieved',
    //COMMANDS_USED: 'Commands used',
    EVENTS_RECIEVED: 'События',
    COMMANDS_USED: 'Командыs',
    MESSAGES_RECIEVED: 'Сообщений П',
    MESSAGES_SENT: 'Сообщений О',
    TOOK: (time) => `Заняло ${time}`,
    STATS: 'Статистика Bass',
    // LANG
    LANG_NOT_FOUND: (lang, langsavailable) => `Язык \`${lang}\` не был найден.\nДоступные языки: \`${langsavailable}\``,
    LANG_LANGUAGE_SET: (lang) => `Язык был сменён на \`${lang}\`!`,
    CURRENT_LANGUAGE: (clang, langsavailable) => `**Текущий язык:** \`${clang}\`\n\nДоступные языки: \`${langsavailable}\``,
    LANG_DESCRIPTION: 'Меняет язык сервера/показывает текущий язык',
    // TRANSLATORS / CONTRIBUTORS
    TRANSLATORS_DESCRIPTION: 'Показывает каждого переводчика, который помог перевести Bass на другие языки',
    CONTRIBUTORS_DESCRIPTION: 'Показывает каждого, кто участвовал в проекте Bass',
    // SAY
    SAY_DESCRIPTION: 'Bass повторяет заданное сообщение',
    // SHARD
    SHARD_DESCRIPTION: 'Показывает информацию о шардах/кластерах',
    EMBED_SHARD_DESCRIPTION: (shard, shards, cluster, clusters) => `Этот сервер работает на шарде \`${shard}/${shards}\` и кластере \`${cluster}/${clusters}\``,
    // SUPPORT
    BASS_SUPPORT_SERVER: 'Сервер поддержки Bass',
    // MUSIC
    NODE_BUSY: 'Извините, но аудио узел на этом сервере **в настоящее время занят**, пожалуйста, подождите пару секунд и попробуйте снова.',
    NODE_NOTHING_PLAYING: '**Ничего не играет на этом сервере.**\nМожет включить что-то?',
    NODE_NOTHING_PLAYED: '**Ничего не было проиграно.**',
    NODE_PROCESSING: 'Аудио узел обрабатывает Ваш запрос...',
    H4DEEP_DESCRIPTION: 'Переключает аудио фильтр 4deep',
    NODE_4DEEP_ENABLED: '**Включен фильтр** `4deep`.',
    NODE_4DEEP_DISABLED: '**Выключен фильтр** `4deep`.',
    H8D_DESCRIPTION: 'Переключает аудио фильтр 8D',
    NODE_8D_ENABLED: '**Включен фильтр** `8D`.',
    NODE_8D_DISABLED: '**Выключен фильтр** `8D`.',
    ECHO_DESCRIPTION: 'Переключает аудио фильтр echo',
    NODE_ECHO_ENABLED: '**Включен фильтр** `Echo`.',
    NODE_ECHO_DISABLED: '**Выключен фильтр** `Echo`.',
    NIGHTCORE_DESCRIPTION: 'Переключает аудио фильтр nightcorer',
    NODE_NIGHTCORE_ENABLED: '**Включен фильтр** `Nightcore`.',
    NODE_NIGHTCORE_DISABLED: '**DВыключен фильтр** `Nightcore`.',
    VAPORWAVE_DESCRIPTION: 'Переключает аудио фильтр vaporwave',
    NODE_VAPORWAVE_ENABLED: '**Включен фильтр** `Vaporwave`.',
    NODE_VAPORWAVE_DISABLED: '**Выключен фильтрr** `Vaporwave`.',
    CHORUS_DESCRIPTION: 'Переключает аудио фильтр chorus',
    NODE_CHORUS_ENABLED: '**Включен фильтр** `Chorus`.',
    NODE_CHORUS_DISABLED: '**Выключен фильтр** `Chorus`.',
    KARAOKE_DESCRIPTION: 'Переключает аудио фильтр karaoke',
    NODE_KARAOKE_ENABLED: '**Включен фильтр** `Karaoke`.',
    NODE_KARAOKE_DISABLED: '**Выключен фильтр** `Karaoke`.',
    PULSATOR_DESCRIPTION: 'Переключает аудио фильтр pulsator',
    NODE_PULSATOR_ENABLED: '**Включен фильтр** `Pulsator`.',
    NODE_PULSATOR_DISABLED: '**Выключен фильтр** `Pulsator`.',
    TREMOLO_DESCRIPTION: 'Переключает аудио фильтрs tremolo',
    NODE_TREMOLO_ENABLED: '**Включен фильтр** `Tremolo`.',
    NODE_TREMOLO_DISABLED: '**Выключен фильтр** `Tremolo`.',
    HSURROUND_DESCRIPTION: 'Переключает аудио фильтр surround',
    NODE_SURROUND_ENABLED: '**Включен фильтр** `Surround`.',
    NODE_SURROUND_DISABLED: '**Выключен фильтр** `Surround`.',
    BITRATE_DESCRIPTION: 'Меняет битрейт/качество музыки',
    NODE_CHANGED_BITRATE: (amount) => `Bitrate has been changed to \`${amount}kbps\``,
    NODE_INVALID_BITRATE: 'Please give a proper bitrate from \`8\` to \`512\` (kbps)',
    CLEAR_DESCRIPTION: 'Clears queue',
    CLEARED_QUEUE: 'Queue has been cleared.',
    LOOP_DESCRIPTION: 'Loops current song/queue',
    LOOP_SONG: '**Enabled song loop.**',
    LOOP_QUEUE: '**Enabled queue loop.**',
    LOOP_ALREADY_SONG: 'Song is already looped!',
    LOOP_ALREADY_QUEUE: 'Queue is already looped!',
    LOOP_DISABLED: '**Disabled loop.**',
    LOOP_INVALID: (prefix) => `**Please give a proper loop type** \`(0 - disable, 1 - song, 2 - queue)\`\nFor example: \`${prefix}loop 2\``,
    NOWPLAYING_DESCRIPTION: 'Shows currently playing song',
    NOWPLAYING: 'Now Playing',
    PAUSE_DESCRIPTION: 'Pauses song',
    PAUSED: '**Paused.**',
    RESUME_DESCRIPTION: 'Resumes song',
    RESUMED: '**Resumed.**',
    SHUFFLE_DESCRIPTION: 'Shuffles queue',
    SHUFFLE_SHUFFLING: '**Shuffling queue...**',
    SHUFFLE_SHUFFLED: '**Shuffled queue.**',
    QUEUE_DESCRIPTION: 'Shows current song queue',
    QUEUE_FETCHING: '**Fetching queue...**',
    QUEUE_MORE: (length) => `*.. And ${length} more*`,
    QUEUE_NOWPLAYING: 'Now playing',
    QUEUE_UPNEXT: 'Up next',
    QUEUE_NOTHING: '**Nothing**',
    QUEUE_LENGTH: 'Queue length:',
    QUEUE_FILTERS: 'Filters:',
    QUEUE_BASS_STRENGTH: 'Bass Strength:',
    QUEUE_LOOP: '**Loop:**',
    QUEUE_SONG: 'Song:',
    QUEUE_YES: 'yes',
    QUEUE_NO: 'no',
    QUEUE: 'Queue:',
    SKIP_DESCRIPTION: 'Skips currently playing song',
    SKIPPED: 'Skipped',
    STOP_DESCRIPTION: 'Stops playing, clears queue and leaves voice channel',
    STOPPED: 'Stopped.',
    PREV_DESCRIPTION: 'Shows recently played song',
    RECENTLY_PLAYED: 'Recently played:',
    VOLUME_DESCRIPTION: 'Changes volume',
    VOLUME_CHANGED: (prev, amount) => `**Volume have been changed from \`${prev}%\` to \`${amount}%\`.**`,
    VOLUME_SAME: (amount) => `**Volume is already set to \`${amount}%\`!**`,
    GIVE_PROPER_VOLUME: (current) => `Please give a proper volume from 0 to 500 (%)\nCurrent volume is: \`${current}%\``,
    BASS_DESCRIPTION: 'Changes bass boost strength',
    GIVE_PROPER_BASS: (current) => `Please give a proper bass boost from 0 to 60 (dB)\nCurrent bass boost is: \`+${current}dB\``,
    NODE_BASS_CHANGED_DONATOR: (amount) => `**Changed bass boost strength to** \`+${amount}dB\`\nThank you for supporting Bass!`,
    PLAY_DESCRIPTION: 'Plays song',
    JOINING_VC_ERROR: 'An unknown error occoured upon trying to join your voice channel.\nPlease try again.',
    QUEUED: (url, title) => `Added [${title}](${url}) to queue.`,
    QUEUED_NOW: (url, title) => `[${title}](${url}) will now play.`,
    QUEUE_ENDED: 'Queue ended, i have left the voice channel.',
    PLAYING_ERROR: (error) => `Error occured while trying to play.\nError message: \`${error}\``,
    PLAYING_EVENT_WITH: (bass, volume, bitrate, filters) => `Bitrate: \`${bitrate}kbps\`, Volume: \`${volume}%\`\nFilters applied: *${filters.join(', ') || '*-*'}*\nBass Boost strength: \`+${bass}dB\``,
    PLAY_NO_SONG: 'Please give name or URL of song you want to play.',
    PLAY_NO_VC: 'You are not in a voice channel.',
    PLAY_OTHER_VC: 'You are not in same voice channel as me. Please join my voice channel and try again.',
    PLAY_NO_PERMS_SPEAK: 'I do not have permissions to speak in your voice channel.',
    PLAY_NO_PERMS_CONNECT: 'I do not have permissions to join your voice channel.',
    SEARCHING_ERROR: (error) => `Error occured while searching.\nError message: \`${error}\``,
    SEARCHING_NOT_FOUND: 'No results found for your search query.',
    PLAY_WRONGURL: 'URL You provided seems to be wrong.',
    PLAY_PROCESSING: 'Processing...',
    PLAY_BACKEND_ERROR: 'Backend for processing search results/playlists seems to be down or returned an error.\nPlease send this information to our support server at **https://discord.gg/By3bvFc**!',
    PLAY_QUEUED_PLAYLIST: (size) => `Loaded ${size} songs.`,
    LEAVING_VC: 'Stopping playing and leaving voice channel in 15 seconds if no one will join.',
    LEFT_VC: 'I have stopped playing and left the voice channel due to inactivity.',
    // SUPPORT
    SUPPORT_DESCRIPTION: 'Support server for help with Bass',
    // TTS
    TTS_DESCRIPTION: 'Sends Text to Speech in file',
    TTS_WRONG_LANG: (langs, prefix) => `**Please give supported language!**\nSupported languages: \`${langs.join(', ')}\`\nExample usage: \`${prefix}tts Hello | en\``,
    TTS_ERROR: 'Error occured while getting the file.',
    TTS_WRONG_TXT_LENGTH: 'Text length must be greater than 0 characters and must not exceed 200 characters.',
    TTS_NO_ARGS: (prefix, langs) => `**Please give text and language to generate tts for.**\nExample usage: \`${prefix}tts Hello | en\`\nAvailable languages: \`${langs.join(', ')}\``,
    // IDK
    NONE_VC: 'You have to be in my voice channel to use that command.',
    NONE_NVC: 'I cannot join your voice channel!',
    NONE_NOVC: 'You are not in voice channel!',
    NONE_VCFULL: 'Your voice channel is full!',
    // RELOAD
    RELOAD_DESCRIPTION: 'Reloads Bass',
    RELOADED: 'Reloaded',
    RELOADED_MESSAGE: (time) => `Bass has been successfully reloaded in ${time}.`,
    // VOTE
    VOTE_DESCRIPTION: 'Checks your vote status/gives vote link',
    YOU_VOTED: 'You voted!',
    YOU_DIDNT_VOTE: 'You didn\'t vote!',
    VOTED_MESSAGE: (mention, date, votes) => `You voted for Bass in the last 12 hours!\nThank you, ${mention} for supporting Bass by voting!\nYou voted at: \`${date}\`\nYou voted for Bass ${votes} times.\n\n[Vote link](https://top.gg/bot/590948209925423123/vote)`,
    NOT_VOTED_MESSAGE: (date, votes) => `You didn't vote for Bass in the last 12 hours :(\nYour latest vote was at: \`${date}\`\nYou voted for Bass ${votes} times.\n\nYou can vote for Bass [here](https://top.gg/bot/590948209925423123/vote).`,



    // OTHER
    REQUESTED_BY: 'Requested by',
    OK: 'OK',
    ERROR: 'ERROR'
};
